---
checks:
  method-lines:
    config:
      threshold: 30
engines:
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- node_modules/
- coverage/
- frontend/
